-- auto-generated definition
create table DDAP_SOLDOUT_SNAPSHOT_AUTO
(
    PGM_ID      NUMBER(14)   not null,
    SOLDOUT_SEQ VARCHAR2(20) not null,
    ATTR_PRD_CD NUMBER(14)   not null,
    VALUE       NUMBER(10),
    BROAD_DT    VARCHAR2(50)
)
/
comment on table DDAP_SOLDOUT_SNAPSHOT_AUTO
    is 'DDAP 일시품절 시간별 주문량'
/
CREATE UNIQUE INDEX DTA_OWN.PK_DDAP_SOLDOUT_SNAPSHOT_AUTO ON DDAP_SOLDOUT_SNAPSHOT_AUTO (PGM_ID, ATTR_PRD_CD, BROAD_DT)
/
ALTER TABLE DDAP_SOLDOUT_SNAPSHOT_AUTO
    ADD CONSTRAINT PK_DDAP_SOLDOUT_SNAPSHOT_AUTO PRIMARY KEY (PGM_ID, ATTR_PRD_CD, BROAD_DT);
/
GRANT SELECT, UPDATE, DELETE, INSERT ON DDAP_SOLDOUT_SNAPSHOT_AUTO TO RL_DTA_DML;
GRANT SELECT ON DDAP_SOLDOUT_SNAPSHOT_AUTO TO RL_DTA_SEL;
/
CREATE OR REPLACE PUBLIC SYNONYM DDAP_SOLDOUT_SNAPSHOT_AUTO FOR DDAP_SOLDOUT_SNAPSHOT_AUTO
/
