SELECT A.PGM_ID,
       A.PRD_CD,
       B.ATTR_PRD_REP_CD,
       MAX(C.PGM_NM)         AS PGM_NM,
       MAX(C.BROAD_DT)       AS BROAD_DT,
       MAX(C.BROAD_STR_DTM)  AS BROAD_STR_DTM,
       MAX(C.BROAD_STR_TIME) AS BROAD_STR_TIME,
       MAX(C.CHANL_CD)       AS CHANL_CD,
       SUM(B.SUPLY_APNT_QTY) AS SUPLY_APNT_QTY
FROM SDHUB_OWN.STG_ATP_BROAD_BEF_MNG_M A
         INNER JOIN SDHUB_OWN.STG_ATP_SUPLY_APNT_D B
                    ON A.SUPLY_PLAN_MNG_NO = B.SUPLY_PLAN_MNG_NO
                        AND A.PRD_CD = B.PRD_CD
         INNER JOIN GSBI_OWN.D_BRD_BROAD_FORM_M C
                    ON A.PGM_ID = C.PGM_ID
WHERE A.BROAD_BEF_MNG_PRG_ST_CD <> '0'
  and SUBSTR(B.ATTR_PRD_REP_CD, 0, 1) <> 'P' -- 보석/잡화 는 P001, P002로 시작함
/* 최근 3년 동안의 편성만 추출 */
  AND A.BROAD_DTM BETWEEN ADD_MONTHS(SYSDATE, -36) AND SYSDATE
  AND A.PGM_ID = :pgm_id
  AND A.PRD_CD = :prd_cd
GROUP BY A.PGM_ID,
         A.PRD_CD,
         B.ATTR_PRD_REP_CD
